apiVersion: skaffold/v2beta16
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: elben10/api
      docker:
        dockerfile: images/api/Dockerfile
      sync:
        manual:
          - src: src/api/**/*.py
            dest: /app
            strip: src/api/
    - image: elben10/frontend
      docker:
        dockerfile: images/frontend/Dockerfile
      sync:
        manual:
          - src: src/frontend/src/**/*.tsx
            dest: /app
            strip: src/frontend/
  local:
    concurrency: 0
    useBuildkit: true
deploy:
  helm:
    releases:
      - name: skaffold-helm
        artifactOverrides:
          ApiImage: elben10/api
          FrontendImage: elben10/frontend
        chartPath: charts/todo
profiles:
  - name: development
    patches:
      - op: replace
        path: /build/artifacts/0/docker/dockerfile
        value: images/api/Dockerfile.Development
      - op: replace
        path: /build/artifacts/1/docker/dockerfile
        value: images/frontend/Dockerfile.Development
