FROM python:3.8

WORKDIR /app/

# Install Poetry
RUN pip install poetry && \
    poetry config virtualenvs.create false

# Copy poetry.lock* in case it doesn't exist in the repo
COPY ./src/api/pyproject.toml ./src/api/poetry.lock* /app/

RUN mkdir src && \
    touch src/__init__.py && \
    poetry install

COPY ./src/api/ /app/

CMD ["python", "-m", "uvicorn", "--host", "0.0.0.0", "--port", "80", "--reload", "src.main:app"]